config/routes.rb
Rails.application.routes.draw do

### this list order is important. Was oben steht hat mehr prioritaet.
### For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get 'welcome/index'   ## created by default. http://hostname:port/welcome/index
  root 'welcome#index'    ##created by default.  redirect / to index in welcome_controller.rb

  ## add extra route for the score board with embedded Ruby implementation
  get "scores/index_ruby.html", to: "scores#index_ruby"

  ##create route for scores automatically
  resources :scores

  ## add extra route
  get "scores_ruby", to: "scores#index_ruby"
  get "scores_debug", to: "scores#index_debug"
  get "scores_desc", to: "scores#scores_desc"
  get "scores_updated_at_desc_with_ranking", to: "scores#scores_updated_at_desc_with_ranking"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  validates :score, presence: true, length: { minimum: 1 }
  validates :player, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  ##basic authentication
  #http_basic_authenticate_with name: "over", password: "laylay", except: [:index, :show]

  ##don't check AuthenticityToken
  skip_before_action :verify_authenticity_token

  ## GET /scores/new
  ## page for inputing new score
  def new
    @score = Score.new
  end


  ## POST /scores
  def create
    ##for debug
    #render plain: params[:score].inspect

    ##association
    @score = Score.new(score_params)

    if @score.save  ## if successed, save to db

      ##return html site
      #redirect_to @score     ##redirect to newly added score
      ##or
      redirect_to scores_debug_path  ##redirect to score list

      ##or return json
      #render json: @score, status: :created, location: @score

    else ## if failed, try again

      ##return html site
      ##this calls def new
      render "new"

      ##or return json
      #render json: @score.errors, status: :unprocessable_entity
    end
  end


  def show
    @score = Score.find(params[:id])
  end

  ## method for the old version
  def index_ruby
    ##return all entries
    ##@scores = Score.all

    ##return all entries, sorted
    ##@scores = Score.order :score ##ascendent
    @scores = Score.order("score DESC") ##descendent

    ##sorted with updated_at DESC row, descendent
    @scores_updated_at_desc = Score.order("updated_at DESC")

    ## get rank by referencing @scores_desc
    create_scores_updated_at_desc_with_ranking()

    ##or return json
    #render json: @scores
  end


  ##produce json for high score list
  def scores_desc
    @scores = Score.order("score DESC") ##descendent
    render json: @scores
  end


  ##produce json for socre list with ranking
  def scores_updated_at_desc_with_ranking
    @scores = Score.order("score DESC") ##descendent
    create_scores_updated_at_desc_with_ranking()
    render json: @scores_updated_at_desc_with_ranking
  end


  ##create score list with ranking
  def create_scores_updated_at_desc_with_ranking
    @scores_desc = @scores
    @scores_updated_at_desc = Score.order("updated_at DESC")
    @scores_updated_at_desc_with_ranking = []
    @scores_updated_at_desc.each_with_index do |s_up,i|
      #puts "======"
      #puts "s_up.id: " + s_up.id.to_s + ", " + i.to_s
      #puts "------"
      @scores_desc.each_with_index do |s_d,j|
        #puts "s_d.id::" + s_d.id.to_s + ", s_up.id:" + s_up.id.to_s + ", jPos:" + j.to_s
        if s_up.id.to_i == s_d.id.to_i then ## must do to_i ohtherwise it returns row in table itself
          #puts "MATCH!!"
          #puts j+1
          id = s_d.id
          sc = s_d.score
          p = s_d.player
          ca = s_d.created_at
          ua = s_d.updated_at
          row = {"rank":j+1,"id":id, "score":sc, "player":p, "created_at":ca, "updated_at":ua}
          @scores_updated_at_desc_with_ranking.push(row)
          break
        end
      end
    end
  end


  def index_debug
    ##normal order(createed at)
    #@scores = Score.all

    ##sorted
    @scores = Score.order("score DESC")
  end


  def edit
    @score = Score.find(params[:id])
  end


  def update
    @score = Score.find(params[:id])
    if @score.update(score_params) ## if update successed
      redirect_to @score
    else
      reder "edit"
    end
  end


  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    ## return to normal site
    #redirect_to scores_path

    ##return to debug site
    redirect_to scores_debug_path
  end


  private
    def score_params
      params.require(:score).permit(:score, :player)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overlays Score Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/edit.html.erb
<h1>Edit player</h1>

<%= form_with(model: @score, local: true) do |form| %>
  <% if @score.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@score.errors.count, "error") %>
      prohibited this article from being saved:</h2>
    <ul>
    <% @score.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


<p>
  <%= form.label :score %><br>
  <%= form.text_field :score %>
</p>

<p>
  <%= form.label :player %><br>
  <%= form.text_field :player %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

<%= link_to 'Back', scores_debug_path%>

app/views/scores/index.html.erb
<!DOCTYPE html>

<html lang="de">
<head>

    <!-- ======== Für die Basispage ======= -->

    <meta charset="UTF-8">
    <meta name="author" content="Sebastian Braun  549301"/>

    <title>Overlays</title>

    <!-- ======= Für mobile Geräte =======  -->

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

    <!-- ======= CSS ======= -->

    <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/grid.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/layout.css" type="text/css" media="all">

    <!-- ======= Google Fonts ====== -->

    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>

</head>
<!-- Ende Headbereich -->
<body>
<!-- Header -->
<header id="header" class="shadow1">

    <h1 class="hidden">Overlays Reloaded</h1>
    <h2 class="hidden">Highscoreseite für Overlays reloaded</h2>
    <section class="container">
        <h2 class="hidden">Wir befinden uns im Bereich Logo und Navigation</h2>
    </section>
    <!-- Ende Container -->

    <!-- Responsive Menu -->
    <!--<form id="responsive-menu" action="#" method="post">-->
        <!--<select>-->
            <!--<option value="">Navigation</option>-->
            <!--<option value="index.html">Home</option>-->
            <!--<option value="about.html">About</option>-->
            <!--<option value="contact.html">Kontakt</option>-->
        <!--</select>-->
    <!--</form>-->
</header>
<!-- Ende Header -->


<!-- Beginn Infobox -->
<section class="info">
    <div id="particles-js"></div>

    <h2 class="hidden">Kurzer Infobereich der Webseite</h2>

    <div class="container info minus-margin">
        <header>
            <h1 class="white">OVERLAYS HIGHSCORE</h1>

        </header>
        <hr class="separator">
    </div>
    <!-- Ende Container -->
</section>
<!-- Ende Infobox -->

<section class="container fields">
    <div class="one_half">
        <h2 class="hidden">Erste Box in der Mitte der Webseite mit den Highscores von Overlays</h2>
        <div>
            <figure class="shadow">
                <figcaption>
                    <caption><h2 class="padding-top">Top Scores</h2></caption>
                    <hr class="separatorDark">
                    <table style="width:100%">
                        <tr>
                            <th>
                                <img class="left padding" src="images/crown_70px.png" alt="image der goldenen Krone"/>
                            </th>
                            <th><h3 class="left padding"><%= @scores[0].player %></h3></th>
                            <th><h3 class="right padding"><%= @scores[0].score %></h3></th>
                        </tr>
                        <tr>
                            <th>
                                <img class="left padding" src="images/silver_crown_70px.png" alt="image der silbernen Krone"/>
                            </th>
                            <td><h3 class="left padding"><%= @scores[1].player %></h3></td>
                            <td><h3 class="right padding"><%= @scores[1].score %></h3></td>
                        </tr>
                        <tr>
                            <th>
                                <img class="left padding" src="images/bronze_crown_70px.png" alt="image der bronzenen Krone"/>
                            </th>
                            <td><h3 class="left padding"><%= @scores[2].player %></h3></td>
                            <td><h3 class="right padding"><%= @scores[2].score %></h3></td>
                        </tr>
                    </table>
                    <hr class="separatorDark">
                        <table style="width:100%">
                          <% @scores[3..9].each_with_index do |score, i| %>
                          <tr>
                              <th>
                                 <h3 class="left padding"><%= i+4 %>.</h3>
                              </th>
                              <th><h3 class="left padding padding-left"><%= score.player %></h3></th>
                              <th><h3 class="right padding"><%= score.score %></h3></th>
                          </tr>
                          <% end %>
                        </table>
                        <details>
                            <summary class="downArrow bounce list-style"><img width="40" height="40" alt="arrow icon" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjwhRE9DVFlQRSBzdmcgIFBVQkxJQyAnLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4nICAnaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkJz48c3ZnIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDMyIDMyIiBoZWlnaHQ9IjMycHgiIGlkPSLQodC70L7QuV8xIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjMycHgiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxwYXRoIGQ9Ik0yNC4yODUsMTEuMjg0TDE2LDE5LjU3MWwtOC4yODUtOC4yODhjLTAuMzk1LTAuMzk1LTEuMDM0LTAuMzk1LTEuNDI5LDAgIGMtMC4zOTQsMC4zOTUtMC4zOTQsMS4wMzUsMCwxLjQzbDguOTk5LDkuMDAybDAsMGwwLDBjMC4zOTQsMC4zOTUsMS4wMzQsMC4zOTUsMS40MjgsMGw4Ljk5OS05LjAwMiAgYzAuMzk0LTAuMzk1LDAuMzk0LTEuMDM2LDAtMS40MzFDMjUuMzE5LDEwLjg4OSwyNC42NzksMTAuODg5LDI0LjI4NSwxMS4yODR6IiBmaWxsPSIjMTIxMzEzIiBpZD0iRXhwYW5kX01vcmUiLz48Zy8+PGcvPjxnLz48Zy8+PGcvPjxnLz48L3N2Zz4=" /></summary>
                            <table style="width:100%">

                              <% @scores[10..-1].each_with_index do |score, i| %>
                              <tr>
                              <th>
                                  <h3 class="left padding"><%= i+11 %>.</h3>
                              </th>
                              <td><h3 class="left padding padding-left"><%= score.player %></h3></td>
                              <td><h3 class="right padding"><%= score.score %></h3></td>
                              </tr>
                              <% end %>
                            </table>
                        </details>
                </figcaption>
            </figure>
        </div>
    </div>
    <div class="one_half">
        <h2 class="hidden">Erste Box in der Mitte der Webseite mit den Highscores von Overlays</h2>
        <div>
            <figure class="shadow">
                <figcaption>
                    <caption><h2 class="padding-top">Newest Scores</h2></caption>
                    <hr class="separatorDark">
                    <table style="width:100%" class="margin-top">
                        <tr>
                            <th>
                                <h3 class="left padding"><%= @scores_updated_at_desc_with_ranking[0][:rank] %>.</h3>
                            </th>
                            <th><h3 class="left padding  padding-left"><%= @scores_updated_at_desc_with_ranking[0][:player] %></h3></th>
                            <th><h3 class="right padding"><%= @scores_updated_at_desc_with_ranking[0][:score] %></h3></th>
                        </tr>
                        <tr>
                            <th style="padding-top: 12px">
                                <h3 class="left padding"><%= @scores_updated_at_desc_with_ranking[1][:rank] %>.</h3>
                            </th>
                            <th><h3 class="left padding padding-left"><%= @scores_updated_at_desc_with_ranking[1][:player] %></h3></th>
                            <th><h3 class="right padding"><%= @scores_updated_at_desc_with_ranking[1][:score] %></h3></th>
                        </tr>
                        <tr>
                            <th style="padding-top: 12px">
                                <h3 class="left padding"><%= @scores_updated_at_desc_with_ranking[2][:rank] %>.</h3>
                            </th>
                            <th><h3 class="left padding padding-left"><%= @scores_updated_at_desc_with_ranking[2][:player] %></h3></th>
                            <th><h3 class="right padding"><%= @scores_updated_at_desc_with_ranking[2][:score] %></h3></th>
                        </tr>
                    </table>
                    <hr class="separatorDark">
                    <table style="width:100%">
                      <% @scores_updated_at_desc_with_ranking[3..9].each do |score| %>
                      <tr>
                          <th>
                              <h3 class="left padding"><%= score[:rank] %>.</h3>
                          </th>
                          <th><h3 class="left padding padding-left"><%= score[:player] %></h3></th>
                          <th><h3 class="right padding padding-left"><%= score[:score] %></h3></th>
                      </tr>
                      <% end %>
                    </table>
                        <details>
                            <summary class="downArrow bounce list-style"><img width="40" height="40" alt="arrow icon" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjwhRE9DVFlQRSBzdmcgIFBVQkxJQyAnLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4nICAnaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkJz48c3ZnIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDMyIDMyIiBoZWlnaHQ9IjMycHgiIGlkPSLQodC70L7QuV8xIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjMycHgiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxwYXRoIGQ9Ik0yNC4yODUsMTEuMjg0TDE2LDE5LjU3MWwtOC4yODUtOC4yODhjLTAuMzk1LTAuMzk1LTEuMDM0LTAuMzk1LTEuNDI5LDAgIGMtMC4zOTQsMC4zOTUtMC4zOTQsMS4wMzUsMCwxLjQzbDguOTk5LDkuMDAybDAsMGwwLDBjMC4zOTQsMC4zOTUsMS4wMzQsMC4zOTUsMS40MjgsMGw4Ljk5OS05LjAwMiAgYzAuMzk0LTAuMzk1LDAuMzk0LTEuMDM2LDAtMS40MzFDMjUuMzE5LDEwLjg4OSwyNC42NzksMTAuODg5LDI0LjI4NSwxMS4yODR6IiBmaWxsPSIjMTIxMzEzIiBpZD0iRXhwYW5kX01vcmUiLz48Zy8+PGcvPjxnLz48Zy8+PGcvPjxnLz48L3N2Zz4=" /></summary>
                            <table style="width:100%">

                              <% @scores_updated_at_desc_with_ranking[10..-1].each do |score| %>
                              <tr>
                                  <th>
                                      <h3 class="left padding"><%= score[:rank] %>.</h3>
                                  </th>
                                  <th><h3 class="left padding padding-left"><%= score[:player] %></h3></th>
                                  <th><h3 class="right padding padding-left"><%= score[:score] %></h3></th>
                              </tr>
                              <% end %>
                        </table>
                        </details>
                </figcaption>
            </figure>
        </div>
    </div>
</section>
<!-- end container -->

<!-- Footer  -->
<section class="footer">
    <h2 class="hidden">Hier finden wir den Fußbereich</h2>
    <section class="container">
    <h2 class="hidden">Hier befinden sich Kontaktdaten unserer Firma </h2>
    </section>
    <p class="copyright">2018 Copyright &copy;Overlays Reloaded All rights reserved. </p>
</section>
<!-- Ende Footer -->

<script src="scripts/jquery-3.1.1.min.js"></script>
<script src="scripts/particles.js"></script>
<script src="scripts/app.js"></script>
<script src="scripts/reload.js"></script>

</body>
</html>

app/views/scores/index_debug.html.erb
<h1>DEBUG MODE:</h1>
<h1> score board</h1>


<%= link_to 'new score', new_score_path %>

<table>
  <tr>

    <th>player</th>
    <th>score</th>
    
    <th></th>
  </tr>

  <% @scores.each do |score| %>
    <tr>
      <td><%= score.player %></td>
      <td><%= score.score %></td>

      <td><%= link_to 'Show', score_path(score) %></td>
      <td><%= link_to 'Edit', edit_score_path(score) %></td>
      <td><%= link_to 'Destroy', score_path(score),
                method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/scores/new.html.erb
<h1> new score</h1>

<%= form_with scope: :score, url: scores_path, local: true do |form| %>
  <p>
    <%= form.label :score %><br>
    <%= form.text_field :score %>
  </p>

  <p>
    <%= form.label :player %><br>
    <%= form.text_field :player %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', scores_debug_path  %>

app/views/scores/show.html.erb
<p>
  <strong>score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>player:</strong>
  <%= @score.player %>
</p>

<%= link_to 'Back', scores_debug_path  %>
<%= link_to 'Edit', edit_score_path(@score) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<!-- comment out -->
<%# <%= link_to 'score board', controller: 'scores' %>


<%= link_to "/scores/index.html", "/scores/index.html" %>